let num = [5, 8, 2, 9, 3];

num[3] = 6;     // COM ISSO, ELE COLOCA O VALOR 6 NO INDICE 3, NO CASO ELE TROCA O 9 PELO 6

num.push(7)     // COM ISSO, ELE ADICIONA O NUMERO 7 NO FIM DO VETOR

num.length      // COM ISSO, ELE MOSTRA A QUANTIDADE DE ELEMENTOS QUE TEM NO VETOR

num.sort()      // COM ISSO, ELE COLOCA OS NÚMEROS EM ORDEM CRESCENTE